target: deploy.teleoperator.so101_leader.So101Leader

# Controller settings
shm_name: "ilstd_teleop_controller"
action_dim: 6
action_dtype: "float64"
freq: 100.0

# Device-specific settings
com: /dev/ttyACM0
robot_id: so101_leader
